// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;
using Microsoft.ML.Data;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;

// Configure app
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddPredictionEnginePool<RPModelV1.ModelInput, RPModelV1.ModelOutput>()
    .FromFile("RPModelV1.mlnet");

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});
var app = builder.Build();

app.UseSwagger();

app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
});

// Define prediction route & handler
app.MapPost("/predict",
    async (PredictionEnginePool<RPModelV1.ModelInput, RPModelV1.ModelOutput> predictionEnginePool, string imagePath) =>
    {
        var image = MLImage.CreateFromFile(imagePath);
        var input = new RPModelV1.ModelInput()
        {
            Image = image,
        };

        return await Task.FromResult(predictionEnginePool.Predict(input));
    });

// Run app
app.Run();
